%YAML 1.2
---
- name: Hello Ansible Playbook
  hosts: all
  become: true
  tasks:
   - name: Example from an Ansible Playbook
     ansible.builtin.ping:
   - name: Print
     ansible.builtin.debug:
      msg: "{{ inventory_hostname }} gateway {{ ansible_default_ipv4.gateway }}"
     when: ansible_default_ipv4.gateway is defined
   - name: Install apache
     ansible.builtin.apt:
      name: apache2
   - name: Restart Service
     ansible.builtin.service:
      name: apache2
      state: started
      enabled: true
   - name: Install MariDB
     ansible.builtin.apt:
      name: mariadb-server
   - name: Unistall htop
     ansible.builtin.apt:
      name: htop
      state: absent
   - name: Replace html
     ansible.builtin.template:
      src: templates/index.html.j2
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: u=rw,g=r,o=r
