%YAML 1.2
---
- name: Hello Ansible Playbook Universal
  hosts: all
  become: true
  roles:
   - webserver
   - dbserver
   - role: deploy
     vars:
       artifact: /home/tux/Downloads/2048.zip
   - bootstrap
