%YAML 1.2
---
- name: Hello Ansible Playbook
  hosts: debian
  become: true
  tasks:
   - name: Example from an Ansible Playbook
     ansible.builtin.ping:
   - name: Print
     ansible.builtin.debug:
      msg: "{{ inventory_hostname }} gateway {{ ansible_default_ipv4.gateway }}"
     when: ansible_default_ipv4.gateway is defined      
   - name: Install apache
     ansible.builtin.apt:
      update_cache: true
      name: apache2
   - name: Restart Service
     ansible.builtin.service:
      name: apache2
      state: started
      enabled: true
   - name: Install MariDB
     ansible.builtin.apt:
      name: mariadb-server
   - name: Unistall htop
     ansible.builtin.apt:
      name: htop
      state: absent
   - name: Install Unzip
     ansible.builtin.apt:
      name: unzip
   - name: Install 2048
     ansible.builtin.unarchive:
      src: /home/tux/Downloads/2048.zip
      dest: /var/www/html
      mode: u=rwx,g=rx,o=rx
