# roles/example/tasks/debian.yml
- name: Install web server
  ansible.builtin.apt:
    name: "apache2"
    state: present
- name: Restart Service
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
